In [1]:
#1. Import the numpy package under the name np
import numpy as np

In [3]:
#2. Print the numpy version and the configurationabs
print (np.version)
np.show_config()

<module 'numpy.version' from 'C:\\Users\\FATMA\\anaconda3\\Lib\\site-packages\\numpy\\version.py'>
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/FATMA/anaconda3/Library/include
    lib directory: C:/Users/FATMA/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1868282989520
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
 

In [4]:
#3.Create a null vector of size 10
Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#4. How to find the memory size of any array


In [5]:
#6. Create a null vector of size 10 but the fifth value which is 1
Z = np.zeros(10)
Z[4]=1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [7]:
A = np.arange(10,50)
A

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
#-Not-#
#veri_yapısı[start:stop:step]

#Negatif Adım Değeri ile Dilimleme (Ters Çevirme)
#print(Z[::-1])

#Belirli Aralıktaki Elemanları Ters Çevirme:
#print(Z[1:5][::-1])


In [8]:
#8. Reverse a vector (first element becomes last) 
Z = np.arange(50)
Z = Z[::-1]
Z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [2]:
#9. Create a 3x3 matrix with values ranging from 0 to 8
Z= np.arange(9).reshape(3,3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
#10. Find indices of non-zero elements from [1,2,0,0,4,0]
#0 olmayan elemanların index numrası
A= np.nonzero([1,2,0,0,4,0])
A

(array([0, 1, 4], dtype=int64),)

In [4]:
##### 11. Create a 3x3 identity matrix
#3*3 lük matris oluştur
M = np.eye(3)
M

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
R = np.random.random((3,3,3))
R

array([[[0.67827322, 0.41484667, 0.58628994],
        [0.03481901, 0.13803901, 0.68805947],
        [0.84089569, 0.70656883, 0.8936757 ]],

       [[0.8864544 , 0.69914806, 0.78431177],
        [0.02603007, 0.94500038, 0.23810205],
        [0.76766161, 0.9873526 , 0.1590811 ]],

       [[0.76197538, 0.16375169, 0.01076948],
        [0.81270549, 0.47961577, 0.87331661],
        [0.63089067, 0.9104283 , 0.45794142]]])

In [8]:
# 14. Create a random vector of size 30 and find the mean valueA
R = np.random.random(30)
m= R.mean()
m

0.573928902332327

In [ ]:
# 15. Create a 2d array with 1 on the border and 0 inside

A = np.ar