NUMPY :NUMERICAL PYTHON

In [3]:
import numpy as np

In [4]:
a= np.array([1,2,3,4])
b= np.array([2,4,6,8])
a*b

array([ 2,  8, 18, 32])

In [10]:
# array'in boyutuna bakalım
a.shape

(4,)

In [13]:
# 1*15 boyutunda bir array oluşturalım
numbers = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])


In [16]:
# 1*15'lik arrayi 3*5 lik bir matrise çevirelim(tr)
numbers = numbers.reshape(3,5)
numbers

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [20]:
#ndim: boyut sayısı
#shape: boyut bilgisi
#toplam eleman sayısı
#dtype : array veri tipi

a = np.random.randint(10, size=5)
a.ndim
a.type

1

In [21]:
# sıfırlardan oluşan array oluşturalım
sifir_dizi = np.zeros((3,4))
sifir_dizi

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
# birlerden oluşan array oluşturalım
bir_dizi = np.ones((4,5))
bir_dizi

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
# boş bir array oluşturalım
bos_dizi = np.empty((2,3))
bos_dizi # python da sıfır boş anlamına gelmektedir.
# aşağıda görüldüğü gibi sayılar sıfıra yakınsamaktadır

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [4.45036841e-307, 1.89146896e-307, 7.56571288e-307]])

In [26]:
# arange(x,y, basamak): x'den başlar y'ye kadar (y dahil değil), basamak büyüklüğünde artarak
dizi_aralik = np.arange(10,50,6)
dizi_aralik

array([10, 16, 22, 28, 34, 40, 46])

In [27]:
# matematiksel işlemler için 2 tane dizi oluşturalım
a = np.array([1,2,3])
b = np.array([4,5,6])

In [28]:
print(a+b) # dizi toplaması
print(a-b) # dizi çıkarması
print(b**2) # dizinin kendisi ile çarpımı

[5 7 9]
[-3 -3 -3]
[16 25 36]


In [29]:
# filtreleme
a<2

array([ True, False, False])

In [30]:
# Hadamard çarpımı ve matris çarpımı için2 tane array oluşturalım
a = np.array([[1,2,3],[4,5,6]])
print(a)
b = np.array([[1,2,9],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2 9]
 [4 5 6]]


In [31]:
# Hadamard çarpımı
print(a*b)

[[ 1  4 27]
 [16 25 36]]


In [32]:
# Matris çarpımı
a.dot(b.T)

array([[32, 32],
       [68, 77]])

In [ ]:
# dizinin elemanlarını toplama
print(a)
a.sum()

In [33]:
# dizinin satırlarını toplama
a.sum(axis=1)

array([ 6, 15])

In [34]:
a.sum(axis=0)

array([5, 7, 9])

In [35]:
# rastgele sayı üretme [0,1] arasında Sürekli üniform dağılım - 4*3 matris
rastgele_dizi = np.random.random((4,3))
rastgele_dizi

array([[0.97648895, 0.41026126, 0.90997462],
       [0.42049375, 0.5106472 , 0.92314725],
       [0.95546518, 0.79666296, 0.9384346 ],
       [0.38841606, 0.41227752, 0.17781226]])

In [36]:
dizi2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
dizi2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
# vektör haline getirme
vektor = dizi2D.ravel()
vektor

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# 0 ile 10 arasında (10 hariç) rastgele 5 tam sayı üretir
random_integers = np.random.randint(0, 10, size=5)
print(random_integers)

[8 2 4 9 4]
